### ISSUE TITLE
No funciona el Inquirer en los tests

### ISSUE THREAD

**Issue by javiidiazglez** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-q#1]
@esegredo @amarrerod Hola buenas tardes!

No entendemos por qué no nos funciona el **Inquirer** , hemos probado manualmente mediante console.log y si que funciona, pero en los test no nos funciona.

Estamos trabado con esto durante días, y no sabemos que hacer. Hemos probado eliminar todos los paquetes (_package.json y node_modules_) y nada.

Hubo un commit que sí que funcionaba los tests, pero después no sabemos que pasó que los tests dejaron de funcionar. Probamos cada una y se supone que debería dejar de funcionar.

Mando capturas:
 
![image](https://user-images.githubusercontent.com/72259510/163606629-49d86e60-c97d-495d-bdb1-25302a1f2a22.png)

![image](https://user-images.githubusercontent.com/72259510/163606645-2618dbb2-d159-4291-895c-56db140b747b.png)

Mando capturas también de las dependencias instaladas: (package.json):

![image](https://user-images.githubusercontent.com/72259510/163606702-60002bdd-01c1-44c6-9ac1-bc5d36f724d7.png)

**Comment by javiidiazglez** [comment]
@esegredo @amarrerod

**Comment by esegredo** [comment]
Hola, buenas tardes.

Tendríamos quer mirarlo en profundidad. Lo haremos cuando comencemos a corregir los trabajos.

Saludos.

**Comment by javiidiazglez** [comment]
Vale perfecto gracias. Ya se lo comenté al profesor Alejandro sobre este tema en una tutoría. @esegredo
